### ISSUE TITLE
建议征集

### ISSUE THREAD

**Issue by SinoAHpx** [SinoAHpx/Mirai.Net#28]
如果你觉得`Mirai.NET`现阶段做得还不够好，请回复此issue来说明你的需求是怎么样的，以及你的预期是什么。

**Comment by SinoAHpx** [comment]
+ Blacklist system implementation
+ Conveniently construct `AtMessage`
+ Enhance `GetPlainMessage` to `ToString` (in every data type of messages)

**Comment by SinoAHpx** [comment]
+ Project template based on `YotsmogBot`

**Comment by kxxt** [comment]
- Add a property for the content of `AppMessage`

> 
> ### App
> 
> ```json5
> {
>     "type": "App",
>     "content": "<>"
> }
> ```
> 
> | 名字     | 类型   | 说明    |
> | -------- | ------ | ------- |
> | content  | String | 内容    |

https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/MessageType.md#App

**Comment by SinoAHpx** [comment]
Refer to mirai-core documentation, add more new features:
+ RecallIn: automatically recall sent message in certain time span
