### ISSUE TITLE
[BUG]WebSocket无法收到消息

### ISSUE THREAD

**Issue by aiqinxuancai** [SinoAHpx/Mirai.Net#33]
**发生了什么事？**
WebSocket无法收到消息

**怎么复现？**
基本和demo一样的代码
![image](https://user-images.githubusercontent.com/4475018/156730219-7b257ada-054b-4031-b9b3-93025326f515.png)

**你以为它会做什么？**
全程没有触发异常，MessageManager.SendFriendMessageAsync可以发消息，但是FriendMessageReceiver等收不到任何东西，断点看了下StartWebsocketListenerAsync也是完全没任何消息收到.

**截图**
服务启动正常
![image](https://user-images.githubusercontent.com/4475018/156729734-e20e1a43-a375-4e7e-a5b2-8cd492d1e83d.png)

**环境**
 - 操作系统:win10
 - Mirai版本:2.10.0
 - mirai-api-http:2.5.0
 - 版本:master分支最新

**补充信息**
原因不明，不知道是否是mirai-api-http的问题

**Comment by SinoAHpx** [comment]
试试去掉声明MiraiBot时var关键字前面的using

**Comment by aiqinxuancai** [comment]
> 试试去掉声明MiraiBot时var关键字前面的using

可以了
