### ISSUE TITLE
Bot消息发送速度问题

### ISSUE THREAD

**Issue by kunlan1949** [SinoAHpx/Mirai.Net#7]
我没有其他的机器人项目做比对（我看过别群的机器人速度为1s左右），为什么发送消息的时间需要2-3s，这是正常现象还是框架所限还是我自己程序上的问题呢？

**Comment by AHpxChina** [comment]
这确实是这个库存在的问题，具体原因我也暂时不清楚。

**Comment by SinoAHpx** [comment]
新版本已发布，请鉴赏
