### ISSUE TITLE
新版本看起来还不错，不过文档目前访问404是因为正在重新编辑吗？

### ISSUE THREAD

**Issue by kunlan1949** [SinoAHpx/Mirai.Net#8]

**Comment by SinoAHpx** [comment]
改成sinoahpx.github.io试试

**Comment by SinoAHpx** [comment]
你甚至不愿意给我一个star

**Comment by kunlan1949** [comment]
哈哈哈，我没这个习惯的，不好意思，马上给



***@***.***
 
发件人： AHpx
发送时间： 2021-09-08 17:51
收件人： SinoAHpx/Mirai.Net
抄送： KnigthtKeepers; Author
主题： Re: [SinoAHpx/Mirai.Net] 新版本看起来还不错，不过文档目前访问404是因为正在重新编辑吗？ (#8)
你甚至不愿意给我一个star
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
